### ISSUE TITLE
Code copied from  poru

### ISSUE THREAD

**Issue by parasop** [FerralTeam/Ferralink#1]
Why you didn't give credits to poru even all code from poru, ok

**Comment by Cd-corgi** [comment]
> Why you didn't give credits to poru even all code from poru, ok

Well, actually forgotted about that, i will edit it and give you the credits as you desercerd, we're sorry. I hope that this won't become in a worst thing

**Comment by parasop** [comment]
> > Why you didn't give credits to poru even all code from poru, ok
> 
> Well, actually forgotted about that, i will edit it and give you the credits as you desercerd, we're sorry. I hope that this won't become in a worst thing

ohk no issue we are in support with you

**Comment by Jethalal1234** [comment]
I will also update the docs soon!
